### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by LilyGO** [radikalbytes/fuckin_balls#1]
Hi, I encountered a problem：
Badge_esp32:102: error: 'vector' does not name a type
 vector calibAccel;
 ^
exit status 1
'vector' does not name a type

I check the relevant information online, but ultimately did not solve this problem。

**Comment by LilyGO** [comment]
I have solved this problem, and have successfully compiled and uploaded. Unfortunately, it happened. The screen does not show anything. (Of course I've already tested the SSD1331 routine before, the screen is intact, pins 5 and 4). I feel that there are some problems with my running steps, a lot of files such as .xbm format files are not used. I hope to get your help, thank you very much.

**Comment by LilyGO** [comment]
![screenshot_4](https://user-images.githubusercontent.com/31160602/35219031-d1200d58-ffab-11e7-989b-b0e5059f4f87.png)

**Comment by radikalbytes** [comment]
Hi LilyGO,
Vector definition as a struct:
`struct Vector
{
    float XAxis;
    float YAxis;
    float ZAxis;
};`
is located at MPU6050.h from Jarzebski MPU6050 Triple Axis Gyroscope & Accelerometer Arduino Library at https://github.com/jarzebski/Arduino-MPU6050
.xbm files are Xtended BitMap files with original sprites generated in GIMP. They aren´t  necessary to compile the code but good to know how image2.h sprites are made.
I wrote code for a ESP32 with a SSD1306 OLED display. I don't know if it works on a SSD1331 color OLED. Maybe you have the problem with the OLED display library.
The OLED library used is https://github.com/squix78/esp8266-oled-ssd1306 that haven´t support for SSD1331. 
Can you test OLED UI Library to check that you can use frames and overlays at 60FPS?
Are you using a ESP32 or another uC?
Don´t forget use Average.h from https://github.com/MajenkoLibraries/Average

**Comment by LilyGO** [comment]
Thank you for your detailed and kind guidance. I am pleased that I have found and applied these three libraries yesterday and have already tested the SSD1306 OLED and the program has shown it.

**Comment by LilyGO** [comment]
![Uploading IMG_20180123_110432.jpg…]()
![Uploading IMG_20180123_110507.jpg…]()
![Uploading IMG_20180123_110519.jpg…]()

**Comment by LilyGO** [comment]
![ewq](https://user-images.githubusercontent.com/31160602/35256293-1cead4d4-002e-11e8-9d23-90e39868af2a.jpg)

**Comment by LilyGO** [comment]
![img_20180123_110507](https://user-images.githubusercontent.com/31160602/35256305-2d73f290-002e-11e8-8894-f0105b181860.jpg)

**Comment by LilyGO** [comment]
![img_20180123_110519](https://user-images.githubusercontent.com/31160602/35256314-3ac4a93a-002e-11e8-9fa2-f4cd4ec028c7.jpg)

**Comment by LilyGO** [comment]
The keys and I2C pins are also connected according to the pin map you provide. Of course, I use the development board is Wemos Lolin ESP32. I want to infer the problem based on the test results, but not satisfactory. When the program upload is successful, ESP32 screen quietly without interest.
Finally, I sincerely hope that this problem can be solved. This will benefit me greatly. Of course I will not stop moving forward.

**Comment by radikalbytes** [comment]
I can see that your brown wire is connected to SCL not to SDA and red wire connected to SDA not SCL.
Maybe the program enters in an infinite loop to start the MPU.
Connect it right and check.

**Comment by LilyGO** [comment]
Ok. I have changed the pin. But my screen still does not show graphics. Here I have a question, when there is no MPU6050 connection, the CPU can not be started normally? Or the screen still shows the interface, but no image flipping. The second question is what the two key functions, because I did not see the video and github. Is it beginning to end and switch mode? Finally, there is a presumptuous request. Can I test GitHub's code and experiment? Maybe where should I get some comments? If the startup is successful, I hope you can send me a picture of ESP32 development board running. Thank you for your help and reply. good luck

**Comment by LilyGO** [comment]
Hope to get your help, of course, if successful show. I will give you some development board or module, or OLED screen

**Comment by radikalbytes** [comment]
Hi LilyGO,
I will stay out of my home by holidays to next monday and can't access to my computer.
Can you see "MPU6050 Initialized" at USB port debug in Arduino?
You can put some Serial.println("stepxx") to debug and monitorize code and locate fail.
I use Arduino 1.8.5
Board: ESP32 DEV Module
Flash mode: QIO
Flash Freq: 80MHz 
Flash size 4MB (32Mb)
Using Board WEMOS LOLIN32 don't work for me
Try this config.
What size of flash have your board?
The code have more things that only sand particles. Some sprites in movement and another routine with balls sprites moving and collisioning with acelerometer. A game of life at full screen and a graphic routine to calibrate acelerometer.
You can try too any example with acelerometer or scanning I2C bus to locate and check it

**Comment by LilyGO** [comment]
![screenshot_5](https://user-images.githubusercontent.com/31160602/35428775-f78259f8-02ab-11e8-9cbe-8c5da06df02f.png)

**Comment by LilyGO** [comment]
Before using are DIO，The rest is the same

![screenshot_7](https://user-images.githubusercontent.com/31160602/35428924-92e6184e-02ac-11e8-89ae-38b30963b4d9.png)

**Comment by LilyGO** [comment]
void setup() start.

![screenshot_6](https://user-images.githubusercontent.com/31160602/35428955-bc3b9160-02ac-11e8-93cc-8401245ae930.png)

**Comment by LilyGO** [comment]
![screenshot_2](https://user-images.githubusercontent.com/31160602/35429077-628925fa-02ad-11e8-90be-c742ad16f97c.png)

**Comment by LilyGO** [comment]
while(!mpu.begin(MPU6050_SCALE_2000DPS, MPU6050_RANGE_2G))
  {
    Serial.println("Could not find a valid MPU6050 sensor, check wiring!");
    //yield(); // Do (almost) nothing -- yield to allow ESP32 background functions
    delay(500);
  }
while statement does not respond to the statement. And added below the serial port information "start" did not print

**Comment by radikalbytes** [comment]
I see in pictures that you power MPU PCB with 5v instead 3.3v
Maybe Your MPU is damaged.
Try with 3.3V and check MPU and I2C lines that are 3.3v

**Comment by LilyGO** [comment]
![ww2](https://user-images.githubusercontent.com/31160602/35762289-4f89e534-08cf-11e8-840f-e7430a7e402c.png)

**Comment by LilyGO** [comment]
I bought a new MPU, just arrived three days. I connected according to the way you said, but the situation remains the same. Serial information only I added a print (). The screen is not displayed from start to finish.

For this, I have two inferences. 

First, although it is very presumptuous. I think your program source code may have forgotten to cancel some or some omissions. I sincerely hope you can verify your program again or upload the test video to Youtube. Of course, that would be better.

Second, if your program does not have any problems, then there is only one possibility. My development board has a few omissions, so the problem is even more simple. best wishes. Thank you

**Comment by radikalbytes** [comment]
Are you using git branch "obstacle_and_mask"?
OMG... the good code is in that branch. I seen it now.

**Comment by radikalbytes** [comment]
The video:
https://www.youtube.com/watch?v=s-02eOzMCt8&feature=youtu.be
